name: Build and Release ZIP

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Create plugin ZIP
        run: |
          PLUGIN_SLUG="wordpress-plugin-template-modern"
          mkdir build
          zip -r "build/$PLUGIN_SLUG.zip" . -x "*.git*" "vendor/*" "tests/*" ".github/*" "*.zip"

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: build/wordpress-plugin-template-modern.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
